### ISSUE TITLE
Too strict gem dependencies

### ISSUE THREAD

**Issue by aleksejleonov** [StefanoMartin/AlphaVantageRB#2]
You have very strict (exact major & minor version) dependencies:

```ruby
  s.add_dependency "httparty", "0.15.6"
  s.add_dependency "humanize", "1.7.0"
```
It could lead to conflicts if ruby project use this gem with other gems depending on `httparty` and `humanize`.

I believe, it would be very useful to make dependencies more loose:
```ruby
  s.add_dependency "httparty", ">= 0.15.6"
  s.add_dependency "humanize", ">= 1.7.0"
```

**Comment by aleksejleonov** [comment]
Thank you!

But looks like you require `httparty` `~> 0.15.7` (so, it's require `0.15.*`), while current version of httparty is `0.16.3`.
Same with `humanize` (required `~> 1.7.0`, but current version is `1.8.1`).

I believe, you can be pretty safe restricting only to major part of version.

```ruby
  s.add_runtime_dependency "httparty", ["~> 0.15", ">= 0.15"]
  s.add_runtime_dependency "humanize", ["~> 1.7", ">= 1.7"]
```

**Comment by mruegenberg** [comment]
Hello, 
I believe this is kind of fixed in the Gemfile but not in the gemspec.
There, we have ` s.add_runtime_dependency "httparty", "~>0.15.6", ">= 0.15.6"`

This prevents e.g your FinnHubRB and this to be in the same project together. 
Editing to be only the `>=` part seems to work for having both in one project.

**Comment by StefanoMartin** [comment]
Hi @mruegenberg ,

Thank you for your feedback. 
I noticed that you are working on it. Let me know if or when you are doing a pull request.

I will be happy to accept it and update the gem on Rubygems.l

**Comment by mruegenberg** [comment]
Cheers, made a PR now.
A bit more commits than it should have, but think I didn't break anything.

**Comment by StefanoMartin** [comment]
Update the Gems. Thanks a lot.
I also took your advice to improve and release a better version of FinnhubRB.

I noticed a new endpoint in AlphaVantage for Cryptocurrency. Maybe tomorrow I will push a new release to include that missing endpoint.

I will close this issue.
