### ISSUE TITLE
Reusing client yields inconsistent quotes (wrong data)

### ISSUE THREAD

**Issue by nneubauer** [StefanoMartin/AlphaVantageRB#4]
When querying the same stock twice in a row using the same client the resulting time series returns different data:

````
require 'alphavantagerb'
client = Alphavantage::Client.new key: "YOURAPIKEY"
stock1 = client.stock symbol: "LYPG.FRK"
puts stock1.timeseries.close.first
stock2 = client.stock symbol: "LYPG.FRK"
puts stock2.timeseries.close.first
````

Returns

````
2019-02-08
231.2000
2019-02-08
231.1000
````

Obviously both values should be the same. Using the `Timeseries.new` method to retrieve both seems to be fine.

**Comment by StefanoMartin** [comment]
Hi @nneubauer,
unlucky I cannot do anything about this. 

This is not a bug of my library (that is mainly only a wrapper for the HTTP API), but a problem connected directly with AlphaVantage API.

I tried a couple of time your query  with POSTMAN and I obtained a similar output.

Here the query that you can use to check by yourself:
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=LYPG.FRK&outputsize=compact&apikey=YOURAPIKEY

I invite you to contact them.
I will cose this issue.
