### ISSUE TITLE
Gem for Finnhub API.

### ISSUE THREAD

**Issue by alpha332** [StefanoMartin/AlphaVantageRB#5]
Hi guys,

Just wondering if we can create a new Gem wrapper for Finnhub stock API as well : https://finnhub.io/ . You can access 60 free calls/minute with intraday data going back for many years with Websocket for free. I think this is a way better alternative for alpha vantage. 5 calls/minute is a bit of a headache with alpha vantage.

**Comment by StefanoMartin** [comment]
That sounds great. Initially AlphaVantage had a similar approach but then it restricts its fetching.
I will give a look to see what can be achieved. Thank you for your suggestion.

**Comment by StefanoMartin** [comment]
Done
Github: https://github.com/StefanoMartin/FinnhubRB
Rubygem: https://rubygems.org/gems/finnhubrb
