### ISSUE TITLE
Alpha Vantage is an unlicensed vendor

### ISSUE THREAD

**Issue by myxfinance223** [StefanoMartin/AlphaVantageRB#7]
Hi,

Just want to bring it to you guys' attention that Alpha Vange is distributing market data **illegally** and legal actions have been taken against the company. I suggest you guys to switch to another provider immediately to avoid service disruption. 

Original proof of illegal activity can be found here: https://www.reddit.com/r/algotrading/comments/hnxoy6/beware_alphavantage_is_not_a_licensed_provider/

The following market data has disappeared due to legal actions and more will be coming soon:
+ US real-time data (now they only have end of day data)
+ LSE
+ NSE
+ ASX
+ Torronto stock exchange (TSX)
+ All Nordic exchanges
+ All Baltic exchanges
+ Moscow stock exchange
+ Istanbul stock exchange

I'm just as disappointed as all of you that a great idea was so poorly executed and based on entirely illegal foundation to begin with.

**Comment by StefanoMartin** [comment]
Thank you @myxfinance223 for your post.

Following this news, I think that I will archive this repo as I did with FinnhubRB (for almost the same reason).

It is really a pity.

**Comment by StefanoMartin** [comment]
I received an email from AlphaVantage that assures me that no market data should disappear. I close this issue. Feel free to create a new issue if you noticed that several market will disappear.

**Comment by myxfinance223** [comment]
Unfortunately, they have removed all their intraday data. Apart from the list above, they have been forced to remove data for Italian market, Singapore, New Zealand, Tokyo stock exchange through legal actions. They seem to be in full damage-control mode now that they reached out to you to try to keep the community together.

Keep in my that you are talking to a bunch of guys who are willing to profit off the data belonged to others illegally for more than 3 years. I normally don't have time to write these things but this company is just on another level of bad business practice.
